# Generated by Django 5.2.3 on 2025-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
