# Generated by Django 5.2.3 on 2025-07-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
