# Generated by Django 4.2.7 on 2025-08-21 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicio_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='logo_height',
            field=models.IntegerField(default=70, help_text='Alto del logo en píxeles (20-200px)', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='negocio',
            name='logo_width',
            field=models.IntegerField(default=100, help_text='Ancho del logo en píxeles (20-300px)', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
