# Generated by Django 4.2.7 on 2025-10-08 19:52

from django.db import migrations


def seed_memberships(apps, schema_editor):
    User = apps.get_model('core', 'Usuario')  
    Membership = apps.get_model('core', 'Membership')

    for u in User.objects.all().iterator():
        negocio = getattr(u, 'negocio', None)
        if negocio and getattr(negocio, 'id', None):
            Membership.objects.get_or_create(
                user_id=u.id,
                negocio_id=negocio.id,
                defaults={'rol': 'profesional', 'is_active': True}
            )

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membership'), 
    ]

    operations = [
        migrations.RunPython(seed_memberships, reverse_func),
    ]