# Generated by Django 4.2.7 on 2025-10-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251008_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='negocio',
        ),
        migrations.AlterField(
            model_name='membership',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('admin', 'Administrador')], default='profesional', max_length=50),
        ),
    ]
