# Generated by Django 4.2.7 on 2025-10-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_usuario_negocio_alter_membership_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional')], db_index=True, max_length=20, null=True),
        ),
    ]