# Generated by Django 4.2.7 on 2025-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_membership_rol_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='rol',
            field=models.CharField(
                choices=[('cliente', 'Cliente'), ('profesional', 'Profesional')],
                default='cliente',
                max_length=20
            ),
        ),
    ]