# Generated by Django 4.2.7 on 2025-10-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='profile_picture_url',
        ),
    ]
