# Generated by Django 4.2.7 on 2025-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_profesional_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
