IONIC_ICON_CHOICES = [
    ("bag-add", "Agregar a bolsa / pedido"),
    ("bag-check", "Bolsa con check / confirmado"),
    ("bag-handle", "Bolsa con manija"),
    ("bag-remove", "Eliminar de bolsa"),
    ("bag", "Bolsa de compra"),
    ("bandage", "Curación / Venda"),
    ("barbell", "Gimnasio / Pesas"),
    ("body", "Cuidado corporal"),
    ("briefcase", "Portafolio / Profesional"),
    ("brush", "Cepillo / Belleza"),
    ("build", "Obras / Reparación"),
    ("bus", "Transporte público"),
    ("business", "Negocio / Empresa"),
    ("cafe", "Cafetería"),
    ("calendar-clear", "Calendario vacío"),
    ("calendar-number", "Calendario con fecha"),
    ("calendar", "Calendario general"),
    ("call", "Llamada telefónica"),
    ("camera-reverse", "Cámara frontal"),
    ("camera", "Cámara fotográfica"),
    ("car-sport", "Auto deportivo / privado"),
    ("car", "Auto común"),
    ("card", "Tarjeta de pago"),
    ("caret-back-circle", "Atrás (círculo)"),
    ("caret-back", "Atrás"),
    ("caret-down-circle", "Abajo (círculo)"),
    ("caret-down", "Abajo"),
    ("caret-forward-circle", "Adelante (círculo)"),
    ("caret-forward", "Adelante"),
    ("caret-up-circle", "Arriba (círculo)"),
    ("caret-up", "Arriba"),
    ("cart", "Carrito de compras"),
    ("cash", "Pago en efectivo"),
    ("chatbox-ellipses", "Chat en caja con puntos"),
    ("chatbox", "Chat en caja"),
    ("chatbubble-ellipses", "Burbuja de chat con puntos"),
    ("chatbubble", "Burbuja de chat"),
    ("chatbubbles", "Conversación múltiple"),
    ("checkmark-circle", "Confirmación (círculo)"),
    ("checkmark-done-circle", "Confirmado totalmente"),
    ("checkmark-done", "Confirmado"),
    ("checkmark", "Check simple"),
    ("construct", "Herramientas / Construcción"),
    ("cut", "Tijera / Corte"),
    ("document-attach", "Documento adjunto"),
    ("document-lock", "Documento protegido"),
    ("document-text", "Documento con texto"),
    ("document", "Documento"),
    ("documents", "Varios documentos"),
    ("fast-food", "Comida rápida"),
]